apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: recipe
  description: Recipe App
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=recipe'
spec:
  type: service
  lifecycle: experimental
  owner: default-team
  providesApis:
    - recipe-api
