apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: recipe-api
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: recipe
    apps.tanzu.vmware.com/has-tests: "true"
    apis.apps.tanzu.vmware.com/register-api: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
  - name: api_descriptor
    value:
      type: openapi 
      location:
        path: "/api-docs"  # The path to the api documentation
      owner: default-team   # The team that owns this
      system: recipe
      description: "A set of API endpoints to manage the resources within the recipe app."
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: gitImplementation
    value: libgit2
  - name: gitops_ssh_secret
    value: azure-devops-secret
  source:
    git:
      url: https://ykhadilkar@dev.azure.com/ykhadilkar/Recipe-Api/_git/Recipe-Api
      ref:
        branch: main