apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: recipe-api
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: recipe
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: gitImplementation
    value: "libgit2"
  - name: gitops_ssh_secret
    value: azure-devops-secret
  source:
    git:
      url: ssh://git@ssh.dev.azure.com:v3/ykhadilkar/Recipe-Api/Recipe-Api
      ref:
        branch: main
